title: Online Money Heist
tagline: Make Money Online!
email: onlinemoneyheist@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onlinemoneyheist.ml" 
favicon: /favicon.ico

google_analytics: UA-172670103-1

paginate: 5
paginate_path: "/guides/page:num"

markdown: kramdown
livereload: true
highlighter: rouge

remote_theme: chrisrhymes/bulma-clean-theme
#theme: bulma-clean-theme
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "ProfessorX"
      layout: post
      show_sidebar: true
